web/router.ex
defmodule Astrologer.Router do
  use Astrologer.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Astrologer do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/repos", RepoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Astrologer do
  #   pipe_through :api
  # end
end

lib/astrologer/endpoint.ex
defmodule Astrologer.Endpoint do
  use Phoenix.Endpoint, otp_app: :astrologer

  socket "/socket", Astrologer.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :astrologer, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_astrologer_key",
    signing_salt: "YVaAlEKb"

  plug Astrologer.Router
end

lib/mix/tasks/rethinkdb.migrate.ex
defmodule Mix.Tasks.Database.Migrate do
  use Mix.Task

  import RethinkDB.Query

  @shortdoc "Creates desired table structure in RethinkDB"

  @moduledoc """
    This will connect to the current environment's database and create all missing tables for our schema
  """

  def run(_args) do
    Astrologer.Database.start_link(Application.get_env(:astrologer, Astrologer.Database))
    table_create("repos", %{primary_key: "full_name"}) |> Astrologer.Database.run
  end
end

web/controllers/page_controller.ex
defmodule Astrologer.PageController do
  use Astrologer.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/repo_controller.ex
defmodule Astrologer.RepoController do
  use Astrologer.Web, :controller

  def index(conn, params) do
    {page, ""} = (params["page"] || "1") |> Integer.parse
    conn
    |> assign(:repos, Astrologer.Github.StarredRepo.index(page))
    |> assign(:page, page)
    |> assign(:pages, Astrologer.Github.StarredRepo.pages)
    |> render("index.html")
  end
end

web/views/error_view.ex
defmodule Astrologer.ErrorView do
  use Astrologer.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Astrologer.LayoutView do
  use Astrologer.Web, :view
end

web/views/page_view.ex
defmodule Astrologer.PageView do
  use Astrologer.Web, :view
end

web/views/repo_view.ex
defmodule Astrologer.RepoView do
  use Astrologer.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Astrologer!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/repo/index.html.eex
<table>
  <%= for repo <- @repos do %>
    <tr>
      <td>
        <a href="<%= repo["html_url"] %>">
          <%= repo["full_name"] %>
        </a>
      </td>
      <td><%= repo["description"] %></td>
      <td>
        <a href="<%= repo["homepage"] %>">
          <%= repo["homepage"] %>
        </a>
      </td>
    </tr>
  <% end %>
</table>

<p>
Page <%= @page %> of <%= @pages %>
</p>

<%= if @page>1 do %>
  <a href="<%= repo_path(@conn, :index, page: @page-1) %>">« Previous</a>
<% end %>
<%= if @page<@pages do %>
  <a href="<%= repo_path(@conn, :index, page: @page+1) %>">Next »</a>
<% end %>